# autojump
[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] &&  source ~/.autojump/etc/profile.d/autojump.sh
    autoload -U compinit && compinit -u

export PATH="$HOME/.local/bin:$PATH"

neofetch

alias vim=nvim
alias la='ls -a'

export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin
